### ISSUE TITLE
Acestream

### ISSUE THREAD

**Issue by carlos00** [alesnav/p2ptv-pi#2]
No consigo hacer que funcione Acestream con ningún canal. El texto que recibido es el indicado abajo. Mis distribución de linux es un Debian "wheezy". Gracias.

pi@raspberrypi ~/p2ptv-pi $ ./tv.sh -c acestream://23bfebbef2e0129e0082eebb83b1e00195743788 -o
Cargando canal AceStream acestream://23bfebbef2e0129e0082eebb83b1e00195743788...
Imposible conectar al canal especificado
Reproducción detenida

**Comment by alesnav** [comment]
Hello,

AceStream is not opensource, so the last free version published os NOT compatible with the newest AceStream streams. This is the main reason which causes these errors when trying to play streams...

Sorry, I can not fix it. Closing...
