### ISSUE TITLE
es posible hacerlo fincionar en xbmc openelen con kodi?

### ISSUE THREAD

**Issue by rubbo** [alesnav/p2ptv-pi#4]
Hola,

Intenté instalarlo en mi raspberry pi con openelec y xbmc kodi, 
Me descargué el zip pero al instalarlo desde el xbmc add on, me pone estructura del archivo no valida.
¿podría ser instalado de otra forma en esta distro del xbmc o no es compatible?

Quería probar tu programa ya que estoy teniendo muchos problemas con el p2pstream 

MUCHAS GRACIAS por tu aportación al mundo stream en raspberry!

saludos

**Comment by alesnav** [comment]
Hola,

Se trata de un simple script en bash para ser usado fuera de XBMC/KODI. Es decir, al no ser una extensión para el media center, es normal que te falle si intentas instalarlo ahí.

La verdad es que paré el desarrollo de esto cuando me compré mi segunda raspberry, utilizando una como media center con KODI y la otra para todos mis scripts, desarrollos, web server, etc, por lo que el desarrollo de este script quedó paralizado. Lo he dejado aquí de todas formas por si le es útil a alguien más.

Dicho esto, yo tengo p2pstreams en OpenELEC y me funciona sin problemas, quizás te pueda ayudar con su configuración... ¿Qué es lo que te ocurre?

Gracias por tu comentario! :)

**Comment by alesnav** [comment]
Te voy a resumir la parte de AceStream. Olvídate de hacerlo funcionar con el 90% de los canales desde una Raspberry o cualquier dispositivo con procesador ARM. El software no es de código abierto y lo liberado es de hace bastante tiempo, por lo que se desconoce el funcionamiento de las nuevas versiones de streaming que usa AceStream.

Ahora bien, SopCast a mi me va bastante bien en OpenELEC + p2pstreams. Te dejo el contenido del fichero `/storage/.xbmc/userdata/advancedsettings.xml`, que define el tamaño de los buffers que se usan en KODI:

```
<advancedsettings>
        <network>
                <cachemembuffersize>252420</cachemembuffersize>
                <curlclienttimeout>45</curlclienttimeout>
        </network>
        <gui>
                <algorithmdirtyregions>3</algorithmdirtyregions>
                <nofliptimeout>0</nofliptimeout>
        </gui>
        <videoscanner>
                <ignoreerrors>true</ignoreerrors>
        </videoscanner>
</advancedsettings>
```

Creo recordar que no he tocado nada más en la configuración para que funcione bien.

No te preocupes por la tarjeta. Con 32 GB tienes más que de sobra siempre y cuando no dejes las pelis/series en ella amontonadas. Por ponerte un ejemplo, la mía es de 16 GB y tengo usado solamente el 3% de la partición `/storage`.

**Comment by rubbo** [comment]
Muchas gracias por la exlicacion  del arenavision..y por la ayuda... es una perrada por que hay bastantes canales de acestream y la gente que usa el pc para verlos ya sean windows o linux no tinen probelmas por que se bajan el software al pc y pista..ojala alguien pudiera hacer ingenieria inversa para los amr6-7 de las raspberry

una pregunta tonta.. tengo cuenta en sopcast y acestream pero no encuentro la forma de poner las cuentas en p2pstream...por que pensaba que podia ser un problema por no estar logeado,,pero por lo que me dices,, no..

muchas veces entro en el p2pstream.. en el arenavision y no sale lo de agendatv o no muestra nigua canal, ni sopcast ni acestream..a que puede ser debido?

voy a ver si con el putty puedo modificar advancesettings para dejarlo tal como me muestras en el pantallazo.. si no recuerdo mal hay algun addon que me permite cambiar el advancesetting desde la raspberry,..a ver si lo encuentro..
 
me puedes recomendar, ya que sopcast parece que va bien.. listas para ser agregadas y conseguir mas canales? o con los parsers, que vienen en la lista te es suficiente?
 que tal las listas xml..que creo que se pueden importar y las m3u tb. te lo digo por que parece que palcotv tb ha sucumbido en la lucha contra la nueva ley

de nuevo muchas gracias por tu tiempo y ganas en ayudarme

saludos!!

**Comment by alesnav** [comment]
La verdad es que no he probado a iniciar sesión en la cuenta de AceStream/SopCast porque siempre me ha funcionado (el SopCast digo). Creo que no hay opción para esto en p2pstreams.

Respecto a lo de ArenaVision... cuando no salen canales ni el agendatv suele ser porque la web está bajo un ataque DDoS. No voy a entrar a valorar desde dónde se lanzan, pero piensa mal y acertarás. Sin embargo, creo recordar que livefootball.ws sí que tiene protecciones anti-DDoS, por lo que normalmente funciona. El problema es que no hay demasiados canales en español, por no decir ninguno.

Por mi parte, me vale con las listas que vienen en el paquete de p2pstreams. En su día probé palcoTV, pero perdía el tiempo probando enlaces y enlaces siendo que al final funcionaba un mínimo porcentaje, así que lo desinstalé. Es decir, que no he probado más opciones.

**Comment by rubbo** [comment]
Muchas gracias por la ayuda!
Imagino que el DDoS no tendrá nada que ver con digital - jajajaj...por eso pienso que el futuro sigue siendo las redes P2P y que compartamos ...

parece que si entro por la lista de sopcast y metiendome en el apartado sport si que hay varios canales en ruso con una gran calidad y que se ven.. ahora creo recordar que se puede sincronizar con el audio en español.. habia un addon para ellos...lo que puede ser un puntazo.
Con respecto a palcotv .pasaba lo que tu decias.. solo las listas que estaban muy cuidadaas..
ahora ya han tenido que abandonar..

probé con el livefootball.ws y roja directa.. pero no parece que haya torrents disponibles.. extraño por que no son partidos de especial interes en españa y se suelen coger sin problemas..
una de las cosas que he quitado ha sido el que me saliera la lista de sopcaast al principio ..y asi puedo acceder a los setting del addon para modifcar los valores de cache, VOD, numero de conexiones etc.. a ver si era algo de eso..
tb me pasa que no se queda salvado el Download Modules on Boot, es decir  al apagar y encender la rasp y acceder al p2pstream ..veo que siempre se desactiva.. es raro..

Pero no te voy a dar mas la chapa que ya me has ayudado y mucho!
un saludo y gracias de nuevo!!

De nuevo muchas gracias por todo..
